# Generated by Django 3.2.8 on 2021-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('Code_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Code_directory', models.CharField(max_length=200, null=True)),
                ('Code_user_id', models.IntegerField(null=True)),
                ('Code_challenge_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('Pass_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Pass_user_id', models.IntegerField(null=True)),
                ('Pass_challenge_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('Progress_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Progress_user_id', models.IntegerField(null=True)),
                ('Progress_lesson_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('User_username', models.CharField(max_length=200, null=True)),
                ('User_password', models.CharField(max_length=200, null=True)),
                ('User_email', models.CharField(max_length=200, null=True)),
                ('User_is_admin', models.BooleanField(null=True)),
                ('User_score', models.IntegerField(null=True)),
                ('User_rank', models.CharField(max_length=200, null=True)),
                ('User_pic', models.CharField(max_length=200, null=True)),
                ('User_bio', models.TextField(null=True)),
            ],
        ),
    ]
