# Generated by Django 3.2.7 on 2021-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='Progress_assignment_id',
            field=models.IntegerField(null=True),
        ),
    ]
