# Generated by Django 3.2.7 on 2021-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_progress_progress_assignment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_link',
            fields=[
                ('Share_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Share_user_id', models.IntegerField(null=True)),
                ('Share_lab_id', models.IntegerField(null=True)),
                ('Share_url', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
