# Generated by Django 3.2.7 on 2021-11-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_share_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='Code_directory',
            new_name='Code_filename',
        ),
    ]
