# Generated by Django 3.2.7 on 2021-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('Challenge_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Challenge_tag_id', models.IntegerField(null=True)),
                ('Challenge_question', models.CharField(max_length=200, null=True)),
                ('Challenge_description', models.TextField(null=True)),
                ('Challenge_date', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_name', models.CharField(max_length=200, null=True)),
                ('Lab_score', models.IntegerField(null=True)),
            ],
        ),
    ]
