# Generated by Django 3.2.8 on 2021-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('Challenge_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Challenge_tag_id', models.IntegerField(null=True)),
                ('Challenge_question', models.CharField(max_length=200, null=True)),
                ('Challenge_description', models.TextField(null=True)),
                ('Challenge_date', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge_tag',
            fields=[
                ('Challenge_tag_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Challenge_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge_test_case',
            fields=[
                ('Challenge_answer_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Challenge_answer_challenge_id', models.IntegerField(null=True)),
                ('Challenge_answer_no', models.IntegerField(null=True)),
                ('Challenge_answer_score', models.IntegerField(null=True)),
                ('Challenge_answer_test', models.TextField(null=True)),
                ('Challenge_answer_answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('Lab_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Lab_tag_id', models.IntegerField(null=True)),
                ('Lab_link', models.TextField(null=True)),
                ('Lab_question', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_tag',
            fields=[
                ('Lab_tag_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Lab_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
