# Generated by Django 3.2.8 on 2021-10-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge_test_case',
            old_name='Challenge_answer_ID',
            new_name='Challenge_test_ID',
        ),
        migrations.RenameField(
            model_name='challenge_test_case',
            old_name='Challenge_answer_answer',
            new_name='Challenge_test_answer',
        ),
        migrations.RenameField(
            model_name='challenge_test_case',
            old_name='Challenge_answer_challenge_id',
            new_name='Challenge_test_challenge_id',
        ),
        migrations.RenameField(
            model_name='challenge_test_case',
            old_name='Challenge_answer_no',
            new_name='Challenge_test_no',
        ),
        migrations.RenameField(
            model_name='challenge_test_case',
            old_name='Challenge_answer_score',
            new_name='Challenge_test_score',
        ),
        migrations.RenameField(
            model_name='challenge_test_case',
            old_name='Challenge_answer_test',
            new_name='Challenge_test_test',
        ),
    ]
