# Generated by Django 3.2.7 on 2021-11-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
