# Generated by Django 3.2.7 on 2021-11-07 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_delete_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Lab_detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='Lab_student',
            field=models.ManyToManyField(blank=True, related_name='lab_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
