# Generated by Django 3.2.7 on 2021-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_challenge_challenge_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='Challenge_level',
            field=models.IntegerField(null=True),
        ),
    ]
