# Generated by Django 3.2.7 on 2021-11-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20211107_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='Lab_score',
        ),
    ]
