# Generated by Django 3.2.7 on 2021-11-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_lab_lab_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_lab', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.lab')),
            ],
        ),
    ]
