# Generated by Django 3.2.7 on 2021-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_challenge_challenge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='Challenge_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
