# Generated by Django 3.2.7 on 2021-11-07 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0007_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lab',
            name='Lab_student',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='lab_tag',
            name='Lab_select',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.lab'),
        ),
        migrations.AddField(
            model_name='lab_tag',
            name='Lab_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
