# Generated by Django 3.2.7 on 2021-11-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20211115_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge_in_tag',
            old_name='Challenge_in_tag_Id',
            new_name='Challenge_in_tag_ID',
        ),
        migrations.RenameField(
            model_name='lab_in_tag',
            old_name='Lab_in_tag_Id',
            new_name='Lab_in_tag_ID',
        ),
        migrations.RenameField(
            model_name='lab_tag',
            old_name='Lab_tag_Id',
            new_name='Lab_tag_ID',
        ),
    ]
