# Generated by Django 3.2.7 on 2021-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20211107_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_tag',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
