# Generated by Django 3.2.7 on 2021-11-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20211116_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Lab_img',
            field=models.TextField(null=True),
        ),
    ]
