# Generated by Django 3.2.7 on 2021-11-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_lab_lab_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='Lab_img',
            new_name='Lab_pic',
        ),
    ]
