# Generated by Django 3.2.7 on 2021-11-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_lab_lab_cover_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='Lab_question',
            new_name='Lab_description',
        ),
    ]
