# Generated by Django 3.2.7 on 2021-11-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_rename_lab_question_lab_lab_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Challenge_date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
