# Generated by Django 3.2.6 on 2022-01-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_rename_challenge_date_lab_lab_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='Challenge_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='Lab_body',
            field=models.TextField(null=True),
        ),
    ]
