# Generated by Django 3.2.6 on 2022-01-25 14:03

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20220125_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='Challenge_body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab',
            name='Lab_body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
