# Generated by Django 3.2.8 on 2021-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('Assignment_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Assignment_lesson_id', models.IntegerField(null=True)),
                ('Assignment_test', models.CharField(max_length=200, null=True)),
                ('Assignment_answer', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Comment_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Comment_lesson_id', models.IntegerField(null=True)),
                ('Comment_user_id', models.IntegerField(null=True)),
                ('Comment_text', models.TextField(null=True)),
                ('comment_reply', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('Lesson_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Lesson_name', models.CharField(max_length=200, null=True)),
                ('Lesson_description', models.TextField(null=True)),
                ('Lesson_link', models.TextField(null=True)),
                ('Lesson_date', models.CharField(max_length=15, null=True)),
                ('Lesson_admin_add', models.IntegerField(null=True)),
                ('Lesson_group_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_group',
            fields=[
                ('Lesson_group_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Lesson_group_name', models.CharField(max_length=200, null=True)),
                ('Lesson_group_description', models.TextField(null=True)),
                ('Lesson_group_admin_id', models.IntegerField(null=True)),
                ('Lesson_group_recent_date', models.CharField(max_length=15, null=True)),
                ('Lesson_group_pic', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
