# Generated by Django 3.2.8 on 2021-10-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_group',
            old_name='Lesson_group_admin_id',
            new_name='Lesson_group_admin_add',
        ),
    ]
