# Generated by Django 3.2.7 on 2021-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_lesson_lesson_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Lesson_cover_pic',
            field=models.TextField(null=True),
        ),
    ]
