# Generated by Django 3.2.7 on 2021-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lesson_lesson_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Assignment_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
