# Generated by Django 3.2.7 on 2021-11-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20211120_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment_date',
            field=models.TextField(null=True),
        ),
    ]
