# Generated by Django 3.2.6 on 2022-01-25 14:03

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_lesson_lesson_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Lesson_body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
